### ISSUE TITLE
Why does typescript/prettier depend on typescript/react?

### ISSUE THREAD

**Issue by IlyaSemenov** [weirdpattern/eslint-config-typescript#1]
See here:
https://github.com/weirdpattern/eslint-config-typescript/blob/6f2990b95e6a09599f9d1bf698e1abeef5d74416/src/prettier.js#L14

Why is that dependency needed? What if I use pure typescript with prettier, why do I need to pull the whole react nonsense?

**Comment by weirdpattern** [comment]
Sorry to keep you waiting, I finally have some time to look into this.
I will have an update by end of day today.
